<?xml version="1.0"?>
<robot name="sensor_d435" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find realsense2_description)/urdf/_materials.urdf.xacro" />
  <xacro:include filename="$(find realsense2_description)/urdf/_usb_plug.urdf.xacro" />

  <xacro:macro name="sensor_d435" params="parent *origin name:=camera use_nominal_extrinsics:=false add_plug:=false use_mesh:=true">
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <xacro:property name="d435_cam_depth_to_infra1_offset" value="0.0" />
    <xacro:property name="d435_cam_depth_to_infra2_offset" value="-0.050" />
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015" />

    <xacro:property name="d435_cam_width" value="0.090" />
    <xacro:property name="d435_cam_height" value="0.025" />
    <xacro:property name="d435_cam_depth" value="0.02505" />
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149" />
    <xacro:property name="d435_glass_to_front" value="0.1e-3" />
    <xacro:property name="d435_zero_depth_to_glass" value="4.2e-3" />
    <xacro:property name="d435_mesh_x_offset" value="${d435_cam_mount_from_center_offset-d435_glass_to_front-d435_zero_depth_to_glass}" />

    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}" />
    <xacro:property name="d435_cam_depth_py" value="0.0175" />
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}" />

    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${name}_bottom_screw_frame" />
    </joint>
    <link name="${name}_bottom_screw_frame" />

    <joint name="${name}_link_joint" type="fixed">
      <origin xyz="${d435_mesh_x_offset} ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0" />
      <parent link="${name}_bottom_screw_frame" />
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <!--visual>
        <xacro:if value="${use_mesh}">
          <origin xyz="${d435_zero_depth_to_glass + d435_glass_to_front} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}" />
          <geometry>
            <mesh filename="package://realsense2_description/meshes/d435.dae" />
          </geometry>
        </xacro:if>
        <xacro:unless value="${use_mesh}">
          <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0" />
          <geometry>
            <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}" />
          </geometry>
          <material name="aluminum" />
        </xacro:unless>
      </visual-->
      <collision>
        <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0" />
        <geometry>
          <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="0.072" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>

  
    <link name="${name}_gazebo" />
    <joint name="${name}_gazebo_joint" type="fixed">
      <parent link="${name}_link"/>
      <child link="${name}_gazebo"/>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
    </joint>
  
    <gazebo reference="${name}_link">
      <sensor name="${name}color" type="camera">
        <camera name="${name}">
          <horizontal_fov>${1.211259}</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>RGB_INT8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <always_on>1</always_on>
        <update_rate>30</update_rate>
        <visualize>1</visualize>
      </sensor>
      <turnGravityOff>false</turnGravityOff>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <sensor type="depth" name="${name}_gazebo_depth">
        <update_rate>30</update_rate>
        <camera>
          <!-- 75x65 degree FOV for the depth sensor -->
          <horizontal_fov>1.5184351666666667</horizontal_fov>
          <vertical_fov>1.0122901111111111</vertical_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>RGB_INT8</format>
          </image>
          <clip>
            <!-- give the color sensor a maximum range of 50m so that the simulation renders nicely -->
            <near>0.01</near>
            <far>50.0</far>
          </clip>
        </camera>
        <plugin name="kinect_controller" filename="libgazebo_ros_openni_kinect.so">
          <baseline>0.2</baseline>
          <alwaysOn>true</alwaysOn>
          <visualize>false</visualize>
          <updateRate>30</updateRate>
          <cameraName>realsense</cameraName>
          <imageTopicName>${name}/color/image_raw</imageTopicName>
          <cameraInfoTopicName>${name}/color/camera_info</cameraInfoTopicName>
          <depthImageTopicName>${name}/depth/image_rect_raw</depthImageTopicName>
          <depthImageInfoTopicName>${name}/depth/camera_info</depthImageInfoTopicName>
          <pointCloudTopicName>${name}/depth/color/points</pointCloudTopicName>
          <frameName>${name}_gazebo</frameName>
          <pointCloudCutoff>0.105</pointCloudCutoff>
          <pointCloudCutoffMax>8.0</pointCloudCutoffMax>
          <distortionK1>0.00000001</distortionK1>
          <distortionK2>0.00000001</distortionK2>
          <distortionK3>0.00000001</distortionK3>
          <distortionT1>0.00000001</distortionT1>
          <distortionT2>0.00000001</distortionT2>
          <CxPrime>0</CxPrime>
          <Cx>0</Cx>
          <Cy>0</Cy>
          <focalLength>0</focalLength>
          <hackBaseline>0</hackBaseline>
        </plugin>
      </sensor>
    </gazebo>
    
    <xacro:if value="${use_nominal_extrinsics}">
      <joint name="${name}_depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_depth_frame" />
      </joint>
      <link name="${name}_depth_frame" />

      <joint name="${name}_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_depth_frame" />
        <child link="${name}_depth_optical_frame" />
      </joint>
      <link name="${name}_depth_optical_frame" />

      <joint name="${name}_infra1_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_infra1_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_infra1_frame" />
      </joint>
      <link name="${name}_infra1_frame" />

      <joint name="${name}_infra1_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_infra1_frame" />
        <child link="${name}_infra1_optical_frame" />
      </joint>
      <link name="${name}_infra1_optical_frame" />

      <joint name="${name}_infra2_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_infra2_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_infra2_frame" />
      </joint>
      <link name="${name}_infra2_frame" />

      <joint name="${name}_infra2_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_infra2_frame" />
        <child link="${name}_infra2_optical_frame" />
      </joint>
      <link name="${name}_infra2_optical_frame" />

      <joint name="${name}_color_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_color_frame" />
      </joint>
      <link name="${name}_color_frame" />

      <joint name="${name}_color_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_color_frame" />
        <child link="${name}_color_optical_frame" />
      </joint>
      <link name="${name}_color_optical_frame" />
    </xacro:if>

    <xacro:if value="${add_plug}">
      <xacro:usb_plug parent="${name}_link" name="${name}_usb_plug">
        <origin xyz="${d435_cam_mount_from_center_offset - 0.02095} ${-d435_cam_depth_py - 0.0353} 0" rpy="0 0 0" />
      </xacro:usb_plug>
    </xacro:if>
  </xacro:macro>
</robot>
